// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqjlrptjcgmjejrzhwca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xamxycHRqY2dtamVqcnpod2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDM0NzIsImV4cCI6MjA2NTU3OTQ3Mn0.g9MtgsgtR139Hlyoc6w45kuynkiF316U5AgsfznJTDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);